site_name: Myfiles
site_url: https://myfiles.readthedocs.io
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - toc.integrate
nav:
  - Home: 'index.md'
  - Reference: 'reference/'
  - Examples:
    - 'Example 1': 'examples/one.json'