site_name: Myfiles
site_url: https://myfiles.readthedocs.io
repo_url: https://github.com/bleonard252/myfiles.git
theme:
  logo: assets/icon.png
  favicon: assets/favicon.ico
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.instant
    - navigation.tabs
    - toc.integrate
  palette:
    primary: green
    accent: purple
plugins:
  - search
markdown_extensions:
  - def_list
  - sane_lists
  - attr_list
nav:
  - Home: 'index.md'
  - For Users:
    - reference/fields.md
    - reference/references.md
    - reference/cards.md
    - reference/verification.md
  - For Developers:
    - reference/lookup.md
    - reference/usernames.md
    - reference/namespacing.md
  - Example Myfiles:
    - examples/
    - 'Example 1': 'examples/one.json'